[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Production environment variables for Vite build
  VITE_API_URL = "https://vibe-tribe-backend-8yvp.onrender.com/api/v1"
  VITE_WS_URL = "wss://vibe-tribe-backend-8yvp.onrender.com"
  VITE_NODE_ENV = "production"
  VITE_FIREBASE_PROJECT_ID = "socialmm-c0c2d"
  VITE_FIREBASE_AUTH_DOMAIN = "socialmm-c0c2d.firebaseapp.com"
  VITE_FIREBASE_STORAGE_BUCKET = "socialmm-c0c2d.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "102259138690885537971"
  VITE_FIREBASE_APP_ID = "1:102259138690885537971:web:a1b2c3d4e5f6g7h8i9j0k1l2"
  VITE_FIREBASE_API_KEY = "AIzaSyDxKQnMpKQH-VxqL8K9X2L5M3N4O6P7Q8R9S0T1"
  # Latest update: Fixed production API URL to point to Render backend

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
