services:
  - type: web
    name: vibe-tribe-backend
    env: node
    plan: free
    buildCommand: npm run render:build
    startCommand: npm run render:start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
